# Generated by Django 4.0.6 on 2022-08-09 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='vegetables',
            options={'verbose_name': 'Овощи', 'verbose_name_plural': 'Овощи'},
        ),
        migrations.AddField(
            model_name='vegetables',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vegetables', to='product.categories'),
        ),
    ]
